image: "registry.gitlab.com/unconed/use.gpu:ci"
stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - rust/use-gpu-text/target/

before_script:
  - yarn install --frozen-lockfile --check-files --non-interactive
  - yarn build-ci
  - echo "@use-gpu:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
  - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc

mr:
  stage: build
  script:
    - echo "Build succeeded"
  rules:
    - if: $CI_MERGE_REQUEST_ID

ci:
  stage: build
  script:
    - echo "Build succeeded"
  rules:
    - if: $CI_COMMIT_BRANCH == "ci"

publish:
  stage: build
  script:
    - echo "Publishing..."
    - ./scripts/npm-publish.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "rc"

