import path from 'path';
import fs from 'fs';
import glob from 'glob';

import { loadModule } from '@use-gpu/shader/wgsl';

const PACKAGE_JSON = './package.json';
const TYPEDEF_TS = './types/wgsl-files/index.d.ts';
const TARGET = '../../build/packages/wgsl';

const files = glob.sync('./**/*.wgsl');

const escape = (s: string) => JSON.stringify(s.toString());
const serialize = (s: any) => JSON.stringify(s, null, 2);

const keys: string[] = [];
const paths: string[] = [];
const modules: any[] = [];

const copyToTarget = (file: string) => {
  const target = path.join(TARGET, file);
  const dir = path.dirname(target);
  fs.mkdirSync(dir, {recursive: true});
  fs.copyFileSync(file, target);
}

const copyToTargetRoot = (file: string) => {
  const target = path.join(TARGET, file);
  const rooted = target.replace('/src/', '/');
  fs.copyFileSync(target, rooted);
}

for (const file of files) {
  const keys = file.split('/');

  const id = keys.pop()!.replace(/\.wgsl$/, '');
  const tokens = [...keys.slice(1), id];
  const name = tokens.join('/');

  copyToTarget(file);

  const code = fs.readFileSync(file).toString();
  const module = loadModule(code, file);

  paths.push(file);
  modules.push(module);
}

// Update exports in package.json
try {
  const PKG = JSON.parse(fs.readFileSync(PACKAGE_JSON).toString());
  PKG.main = 'src/index.ts';
  PKG.exports = {".":
    {
      "types": "./types/wgsl-files/index.d.ts",
      "default": "./src/index.ts"
    },
  };
  for (let path of paths) {
    PKG.exports[path.replace('src/', '')] = {
      "types": path.replace(/.wgsl$/, '.wgsl.d.ts'),
      "import": path,
      "require": path,
    };
  }
  const json = JSON.stringify(PKG, null, 2);
  fs.writeFileSync(PACKAGE_JSON, json);
} catch (e) {}

// Generate type definition
const makeTSModule = (file: string, symbols?: string[]) => {
  const pattern = file.replace('./src/', '@use-gpu/wgsl/');
  return `declare module ${escape(pattern)} {
  type ParsedBundle = import('@use-gpu/shader').ParsedBundle;
  const __module: ParsedBundle;
  ${(symbols ?? []).map(s => `export const ${s}: ParsedBundle;`).join("\n  ")}
  export default __module;
}
`
};

files.map((file, i) => {
  const typeDef = makeTSModule(file, modules[i].table.visibles);
  const dts = file.replace(/\.wgsl$/, '.wgsl.d.ts');
  fs.writeFileSync(dts, typeDef);
  copyToTarget(dts);
});

const typeDef = [
  `// File generated by build.ts. Do not edit directly.
  `,
  ...files.map((file, i) => makeTSModule(file, modules[i].table.visibles)),
].join("\n");

fs.writeFileSync(TYPEDEF_TS, typeDef);
copyToTarget(TYPEDEF_TS);
